require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'client/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

AsciiComments:
  Enabled: false